Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: fecp4-1022-lab2-ralim-s3
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04dd23e62ed049936
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: subnet-0e5570f6ec2cf0555
          GroupSet:
            - sg-0fd48a2beac0f14ee